import Head from "next/head";
import About from "../src/components/About";
import Hero from "../src/components/Hero";
import { sanityClient } from "../sanity";
import Works from "../src/components/Works";

export default function Home({ siteSettings, projects }) {
  return (
    <main className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Section */}
      <Hero {...siteSettings} />
      {/* About Section */}
      <About />
      {/* Works Section */}
      <Works projects={projects} />
      {/* Create Section */}
    </main>
  );
}

export const getStaticProps = async () => {
  const query = `*[_type == "projects"]`;

  const projects = await sanityClient.fetch(query);

  const query2 = `*[_type == "siteSettings"][0]`;

  const siteSettings = await sanityClient.fetch(query2);

  if (!projects || !siteSettings) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      projects,
      siteSettings,
    },
  };
};
