import Head from "next/head";
import About from "../src/components/About";
import Hero from "../src/components/Hero";

export default function Home() {
  return (
    <main className="flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Section */}
      <Hero />

      {/* About Section */}
      <About />
      {/* Works Section */}
      {/* Create Section */}
    </main>
  );
}
